name: gg_fake_timer
description: A class faking dart's Timer class. Can be used for test scenarios.
version: 1.0.0
repository: https://github.com/inlavigo/gg_fake_timer

environment:
  sdk: ">=3.2.0 <4.0.0"

# Add regular dependencies here.
dev_dependencies:
  args: ^2.4.2
  lints: ^3.0.0
  pana: ^0.21.45
  test: ^1.25.0
