name: gg_fake_timer
description: A class faking dart's Timer class. Can be used for tests.
version: 0.9.0
homepage: https://github.com/inlavigo/gg_fake_timer

environment:
  sdk: ^3.0.0-213.0.dev

# Add regular dependencies here.
dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.0
